# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sieveman < Formula
  desc "Universal ManageSieve protocol client"
  homepage "https://github.com/dominicpratt/sieveman"
  version "0.6.0"
  license "ISC"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dominicpratt/sieveman/releases/download/v0.6.0/sieveman_0.6.0_darwin_amd64.tar.gz"
      sha256 "a133a3a677e7f812efeec5c0047ba28288cfb7794c5c5dd4ea9b7bf26518d41b"

      define_method(:install) do
        bin.install "sieveman"
        man1.install "sieveman.1"
        bash_completion.install "sieveman.bash" => "sieveman"
        zsh_completion.install "sieveman.zsh" => "_sieveman"
        fish_completion.install "sieveman.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dominicpratt/sieveman/releases/download/v0.6.0/sieveman_0.6.0_darwin_arm64.tar.gz"
      sha256 "0da15d2aa4a9df825459f79651fbfacfd7fc521f6d159db2cbd70bcb9422b65a"

      define_method(:install) do
        bin.install "sieveman"
        man1.install "sieveman.1"
        bash_completion.install "sieveman.bash" => "sieveman"
        zsh_completion.install "sieveman.zsh" => "_sieveman"
        fish_completion.install "sieveman.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dominicpratt/sieveman/releases/download/v0.6.0/sieveman_0.6.0_linux_amd64.tar.gz"
      sha256 "32702b46d452ab24756532dfb078c4b6d41285bf923398f2f7c24b0297822d78"
      define_method(:install) do
        bin.install "sieveman"
        man1.install "sieveman.1"
        bash_completion.install "sieveman.bash" => "sieveman"
        zsh_completion.install "sieveman.zsh" => "_sieveman"
        fish_completion.install "sieveman.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dominicpratt/sieveman/releases/download/v0.6.0/sieveman_0.6.0_linux_arm64.tar.gz"
      sha256 "e1903e1c90b111560fadcc2a3c06e5fcaa8af9931b10d7d3a83eb74009f0d520"
      define_method(:install) do
        bin.install "sieveman"
        man1.install "sieveman.1"
        bash_completion.install "sieveman.bash" => "sieveman"
        zsh_completion.install "sieveman.zsh" => "_sieveman"
        fish_completion.install "sieveman.fish"
      end
    end
  end

  test do
    assert_match "Sieveman #{version}", shell_output("#{bin}/sieveman version")
  end
end
